- name: copy Vault policy configuration files
  copy:
    src: "{{policy_dir}}"
    dest: "/tmp/"
    mode: '0644'

- name: get policy files list
  shell: ls /tmp/policy
  register: policy_files

- name: copy Vault approles configuration files
  copy:
    src: "{{approles_dir}}"
    dest: "/tmp/"
    mode: '0644'

- name: get approles files list
  shell: ls /tmp/approles
  register: approles_files

- name: write Vault policies
  command: vault policy write {{ item[:-5] }} /tmp/policy/{{item}}
  loop: "{{policy_files.stdout_lines}}"

- name: enable Vault Approle authentication
  command: vault auth enable approle

- name: write Vault approles
  command: vault write auth/approle/role/{{ item[:-5] }} @/tmp/approles/{{item}}
  loop: "{{approles_files.stdout_lines}}"
