- name: copy Vault policy configuration files
  copy:
    src: "{{policy_dir}}"
    dest: "/tmp/"
    mode: '0644'

- name: get policy files list
  shell: ls /tmp/policy
  register: policy_files

- name: copy Vault approles configuration files
  copy:
    src: "{{approles_dir}}"
    dest: "/tmp/"
    mode: '0644'

- name: get approles files list
  shell: ls /tmp/approles
  register: approles_files

- name: write SOPS policy
  command: vault policy write sops-policy /tmp/policy/sops-policy.json

- name: write database policy
  command: vault policy write {{ database_name }}-policy /tmp/policy/{{database_name}}-policy.json

- name: enable Vault Approle authentication
  command: vault auth enable approle

- name: write SOPS approle
  command: vault write auth/approle/role/sops-approle @/tmp/approles/sops-approle.json

- name: write database approle
  command: vault write auth/approle/role/{{ database_name }}-approle @/tmp/approles/{{database_name}}-approle.json
  
- name: get SOPS approle role_id
  command: vault read auth/approle/role/sops-approle/role-id
  register: sops_role_id

- name: get SOPS approle secret_id
  command: vault write -f auth/approle/role/sops-approle/secret-id
  register: sops_secret_id

- name: get database approle role_id
  command: vault read auth/approle/role/{{database_name}}-approle/role-id
  register: db_role_id

- name: get database approle secret_id
  command: vault write -f auth/approle/role/{{database_name}}-approle/secret-id
  register: db_secret_id
  
