- name: download SOPS binary
  get_url:
    url: https://github.com/getsops/sops/releases/download/v3.12.2/sops-v3.12.2.linux.amd64
    dest: /usr/local/bin/sops
    mode: '0755'

- name: add environment variables for SOPS
  lineinfile:
    path: /etc/environment
    line: "{{item}}"
    state: present
  loop:
    - "export EDITOR=nano"
    - "export VAULT_ADDR=https://vault-system"

- name: activate environment variables
  shell: source /etc/environment
  become: false
