- name: download SOPS binary
  get_url:
    url: https://github.com/getsops/sops/releases/download/v3.12.2/sops-v3.12.2.linux.amd64
    dest: /usr/local/bin/sops
    mode: '0755'

- name: set VAULT_ADDR environment variable
  copy:
    src: "{{conf_dir}}/sops_environment"
    dest: /etc/environment
    mode: '0644'

- name: activate environment variables
  shell: source /etc/environment
  become: false
